"use client";

import { useMemo, useState } from "react";
import { Bot, Filter, Search, Sparkles } from "lucide-react";
import { DEMO_ROWS } from "@/lib/bogota-apartments/data";

export function ConsultasView() {
  const [zone, setZone] = useState("Todas");
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState(false);
  const rows = useMemo(() => zone === "Todas" ? DEMO_ROWS : DEMO_ROWS.filter(row => row.zone === zone), [zone]);
  return (
    <div className="bg-[#eef0ec]">
      <section className="mx-auto max-w-[1480px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><p className="font-mono text-[10px] uppercase tracking-[.22em] text-violet-700">Consultas / Laboratorio</p><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_.55fr] lg:items-end"><h1 className="text-5xl font-medium leading-[.9] tracking-[-.055em] sm:text-8xl">Preguntas claras.<br /><span className="text-violet-700">Resultados trazables.</span></h1><p className="text-base leading-relaxed text-slate-600">Prueba la experiencia que tendrá el proyecto. Los resultados actuales son una muestra de interfaz y no datos reales del mercado.</p></div></section>
      <section className="mx-auto grid max-w-[1480px] border-y border-[#07111d]/20 bg-white lg:grid-cols-[300px_1fr]">
        <aside className="border-b border-[#07111d]/20 p-6 lg:border-b-0 lg:border-r lg:p-8"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em]"><Filter size={14} /> Filtros</div><label className="mt-8 block text-xs font-semibold">Zona</label><select value={zone} onChange={event => setZone(event.target.value)} className="mt-2 w-full border border-[#07111d]/25 bg-transparent px-3 py-3 text-sm"><option>Todas</option>{DEMO_ROWS.map(row => <option key={row.zone}>{row.zone}</option>)}</select><label className="mt-6 block text-xs font-semibold">Tipo</label><select className="mt-2 w-full border border-[#07111d]/25 bg-transparent px-3 py-3 text-sm"><option>Todos</option><option>Apartamento</option><option>Casa</option></select><p className="mt-8 border-l-2 border-fuchsia-500 pl-3 text-xs leading-relaxed text-slate-500">Filtros activos sobre una muestra estática. La integración real se hará con Inmodata Queries API.</p></aside>
        <div className="overflow-x-auto p-6 lg:p-10"><div className="mb-7 flex items-center justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.2em] text-violet-700">Resultado</p><h2 className="mt-2 text-2xl font-semibold">Muestra de observaciones</h2></div><span className="bg-[#d9ff48] px-3 py-2 font-mono text-[9px] uppercase tracking-[.15em]">Demo</span></div><table className="w-full min-w-[620px] border-collapse text-left text-sm"><thead className="border-y border-[#07111d]/20 font-mono text-[9px] uppercase tracking-[.16em] text-slate-500"><tr><th className="py-4">Zona</th><th>Tipo</th><th>Área</th><th>Periodo</th></tr></thead><tbody>{rows.map(row => <tr key={row.zone} className="border-b border-[#07111d]/10"><td className="py-5 font-semibold">{row.zone}</td><td>{row.property}</td><td>{row.area}</td><td className="text-fuchsia-700">{row.period}</td></tr>)}</tbody></table></div>
      </section>
      <section className="bg-[#d9ff48]"><div className="mx-auto grid max-w-[1480px] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-12 lg:py-24"><div><Bot size={28} /><h2 className="mt-6 text-4xl font-medium leading-none tracking-[-.04em] sm:text-6xl">Pregunta con tus propias palabras.</h2><p className="mt-6 max-w-md text-sm leading-relaxed">La respuesta final citará datasets y filtros. Por ahora, este asistente solo demuestra el flujo.</p></div><div className="self-center"><label htmlFor="ai-question" className="font-mono text-[9px] uppercase tracking-[.18em]">Pregunta de ejemplo</label><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input id="ai-question" value={question} onChange={event => { setQuestion(event.target.value); setAnswer(false); }} placeholder="¿Qué zonas puedo comparar y por qué?" className="min-h-14 flex-1 border border-[#07111d] bg-transparent px-4 text-sm placeholder:text-[#07111d]/50" /><button onClick={() => setAnswer(true)} className="flex items-center justify-center gap-2 bg-[#07111d] px-6 py-4 text-sm font-bold text-white">Consultar <Sparkles size={16} /></button></div>{answer && <div className="mt-4 border border-[#07111d]/30 bg-white/55 p-5"><p className="flex items-center gap-2 text-xs font-bold"><Search size={14} /> Respuesta de demostración</p><p className="mt-3 text-sm leading-relaxed">Cuando la API esté conectada, aquí aparecerá una síntesis basada en los datos filtrados, junto con las fuentes, el periodo y las limitaciones del análisis. Tu pregunta fue: “{question || "consulta sin texto"}”.</p></div>}</div></div></section>
    </div>
  );
}
